### ISSUE TITLE
LoRaWANPacket.print

### ISSUE THREAD

**Issue by Samuel-ZDM** [ricaun/LoRaWanPacket#2]
Hello!

It’s me here again with doubts. Sorry for the inconvenience.

I am studying your code and could not find the definition of the LoRaWanPacket.print () function.
I'm looking for the definition of it because I wanted to send a byte vector instead of a char vector because I'm using the TTN with the Cayenne payload and I can't get it to work with a char vector.

I believe that the LoRaWanPacket.print (" ") function stores the data in the buffer to be used in the encode function.

Sorry about the questions.

Thank you very much in advance.

**Comment by ricaun** [comment]
Hello,

Actually, the library uses the `Stream` class.

To use CayenneLPP check the example below. I usually use https://github.com/ElectronicCats/CayenneLPP

```
#include <CayenneLPP.h>

void LoRa_sendMessage()
{
  LoRa_TxMode();
  LoRaWanPacket.clear();
  PayloadNow(LoRaWanPacket);
  if (LoRaWanPacket.encode())
  {
    LoRa.beginPacket();
    LoRa.write(LoRaWanPacket.buffer(), LoRaWanPacket.length());
    LoRa.endPacket(true);
  }
}

void PayloadNow(Stream &out)
{
  CayenneLPP lpp(64);

  lpp.addVoltage(1, 3.3);
  
  out.write(lpp.getBuffer(), lpp.getSize());
}
```

See yaa!

**Comment by Samuel-ZDM** [comment]
Very good!

It worked just fine.

Thank you very much for your help!
